# Generated by Django 5.0.9 on 2026-08-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='visible_compra',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='visible_venta',
            field=models.BooleanField(default=True),
        ),
    ]
