# Generated by Django 5.0.9 on 2026-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(default='Registrado', max_length=20),
        ),
    ]
