# Generated by Django 5.0.9 on 2026-08-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_producto_visible_compra_producto_visible_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
