# Generated by Django 5.0.9 on 2026-05-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_rol_fk_empresa_modulo_permisorol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaturno',
            name='observaciones_cierre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
