# Generated by Django 5.0.9 on 2026-08-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_productovariante_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='monto_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
