# Generated by Django 5.0.9 on 2026-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_pagoventa_monto_aplicado_pagoventa_monto_recibido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoventa',
            name='monto',
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='monto_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
