# Generated by Django 5.0.9 on 2026-06-04 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_cajaturno_observaciones_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaturno',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('CERRADA', 'CERRADA')], default='ABIERTA', max_length=20),
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='monto_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='observaciones_apertura',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='saldo_teorico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_entrega',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cajaturno',
            name='cajachica_apertura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cajaturno',
            name='monto_cierre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cajaturno',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cajaturno',
            name='monto_qr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APERTURA', 'Apertura'), ('VENTA', 'Venta'), ('INGRESO', 'Ingreso Monetario'), ('EGRESO', 'Egreso Monetario'), ('CIERRE', 'Cierre')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caja_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='gym.cajaturno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimiento_caja',
                'ordering': ['created_at'],
            },
        ),
    ]
