# Generated by Django 5.0.9 on 2026-06-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_cajaturno_diferencia_cajaturno_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaturno',
            name='monto_online',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
