# Generated by Django 5.0.9 on 2026-08-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_remove_pagoventa_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='monto_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
