# Generated by Django 5.0.9 on 2026-06-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_cajaturno_monto_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='moneda',
            field=models.CharField(choices=[('BOB', 'Boliviano'), ('USD', 'Dólar'), ('ARS', 'Peso Argentino'), ('CLP', 'Peso Chileno')], default='BOB', max_length=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pie_ticket',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='simbolo_moneda',
            field=models.CharField(default='Bs.', max_length=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tema',
            field=models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=10),
        ),
    ]
