# Generated by Django 5.0.9 on 2026-08-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_pagoventa_monto_alter_pagoventa_monto_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresomonetario',
            name='metodo_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gym.metodopago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresomonetario',
            name='metodo_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gym.metodopago'),
            preserve_default=False,
        ),
    ]
