# Generated by Django 5.0.9 on 2026-08-19 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_remove_pagoventa_monto_egresomonetario_metodo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_declarado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caja_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos', to='gym.cajaturno')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.metodopago')),
            ],
            options={
                'db_table': 'arqueo_caja',
                'unique_together': {('caja_turno', 'metodo_pago')},
            },
        ),
    ]
