# Generated by Django 5.0.9 on 2026-06-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_empresa_moneda_empresa_pie_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='moneda',
            field=models.CharField(choices=[('BOB', 'Boliviano'), ('GUY', 'Guaraní'), ('USD', 'Dólar'), ('ARS', 'Peso Argentino'), ('CLP', 'Peso Chileno')], default='BOB', max_length=5),
        ),
    ]
