# Generated by Django 5.0.9 on 2026-09-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_remove_pagoventa_monto_arqueocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventas', models.JSONField(blank=True, default=dict, help_text='Configuración del módulo de ventas')),
                ('compras', models.JSONField(blank=True, default=dict, help_text='Configuración del módulo de compras')),
                ('cierre_caja', models.JSONField(blank=True, default=dict, help_text='Configuración del cierre de caja')),
                ('ticket', models.JSONField(blank=True, default=dict, help_text='Configuración de tickets impresos')),
                ('sistema', models.JSONField(blank=True, default=dict, help_text='Configuración general del sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='gym.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
                'db_table': 'configuracion_empresa',
            },
        ),
    ]
